### ISSUE TITLE
会有webdriver问题吗？user-data-dir问题

### ISSUE THREAD

**Issue by gMan1990** [zqjzqj/mtSecKill#103]
```plain
> window.navigator.webdriver
true
```

所以对`-execPath`可否增加设置user-data-dir的参数

**Comment by zqjzqj** [comment]
目录是自动生成的 在临时目录下 如果你想要自定义目录 或者用已有浏览器的用户目录的话 可以自行修改代码哦

**Comment by gMan1990** [comment]
@zqjzqj 1. 是临时目录，那没问题了 2. 哈哈，我不是go，不想装环境来编译 :dog

**Comment by gMan1990** [comment]
emm. 不支持`ver 62.0.3202.89`，`webdriver`怎么办 :sad

**Comment by gMan1990** [comment]
@zqjzqj 不支持Chrome 62，`webdriver`怎么办，:sad
