### ISSUE TITLE
1.14 已经购的2瓶,做了小修改.感谢作者大大

### ISSUE THREAD

**Issue by liuzantian** [zqjzqj/mtSecKill#119]

**Comment by chaixuhua** [comment]
恭喜恭喜

**Comment by hongyubaobao** [comment]
做了啥小修改？

**Comment by rot9** [comment]
@liuzantian 你不需要设置密码吗？我也没看到哪里可以设置支付密码啊

**Comment by ruixule** [comment]
截图，我看下？？？

**Comment by waluan88** [comment]
是不是有特别的设置 啊

**Comment by liuzantian** [comment]
的确需要输入支付密码,抢购后 自动跳订单点击付款, 小修改就是输入支付密码 和 打开浏览器执行非安全模式,建议下载最新版本Chrome 手动指定路径

**Comment by hongyubaobao** [comment]
> 的确需要输入支付密码,抢购后 自动跳订单点击付款, 小修改就是输入支付密码 和 打开浏览器执行非安全模式,建议下载最新版本Chrome 手动指定路径

非常感谢无私分享！

**Comment by ruixule** [comment]
> 的确需要输入支付密码,抢购后 自动跳订单点击付款, 小修改就是输入支付密码 和 打开浏览器执行非安全模式,建议下载最新版本Chrome 手动指定路径

可以看下订单截图，大佬

**Comment by hongyubaobao** [comment]
> > 的确需要输入支付密码,抢购后 自动跳订单点击付款, 小修改就是输入支付密码 和 打开浏览器执行非安全模式,建议下载最新版本Chrome 手动指定路径
> 
> 可以看下订单截图，大佬

你追着要截图是干啥呢？截图对您有啥用

**Comment by liuzantian** [comment]
我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.

**Comment by ruixule** [comment]
> 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.

还有什么要注意的，大佬

**Comment by Xzw111222** [comment]
> 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.

请问装的什么插件执行的编译，还是使用的``go build``命令呢？

**Comment by liuzantian** [comment]
> 
> 
> > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> 
> 请问装的什么插件执行的编译，还是使用的`go build`命令呢？

cmd 目录下 执行 go build  会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。

**Comment by hongyubaobao** [comment]
> > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > 
> > 
> > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> 
> cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。

为啥要这样执行和设置呢，考虑的是？这些重要么？

**Comment by Xzw111222** [comment]
> > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > 
> > 
> > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> 
> cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。

我这边执行要报错 
```
go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": net/http: TLS handshake timeout
```
请问这是什么原因？还要配置什么不

**Comment by liuzantian** [comment]
vs 里面不指定 浏览器 是无法打开浏览器的哦。我就是偷懒不想吧exe放到 chrome下而已，生成exe 使用 管理员运行成功率高，我也不太明白，

**Comment by ruixule** [comment]
> > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> 
> 请问装的什么插件执行的编译，还是使用的``go build``命代理

代理设置的问题

**Comment by liuzantian** [comment]
> 
> 
> > > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > > 
> > > 
> > > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> > 
> > 
> > cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。
> 
> 我这边执行要报错
> 
> ```
> go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": net/http: TLS handshake timeout
> ```
> 
> 请问这是什么原因？还要配置什么不

根目录 先执行  go install 安全依赖包呀

**Comment by ruixule** [comment]
> > 
> > 
> > > > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > > > 
> > > > 
> > > > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> > > 
> > > 
> > > cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。
> > 
> > 我这边执行要报错
> > 
> > ```
> > go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": net/http: TLS handshake timeout
> > ```
> > 
> > 请问这是什么原因？还要配置什么不
> 
> 根目录 先执行  go install 安全依赖包呀

都说了，代理设置的问题

**Comment by liuzantian** [comment]
> 
> 
> > > > > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > > > > 
> > > > > 
> > > > > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> > > > 
> > > > 
> > > > cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。
> > > 
> > > 
> > > 我这边执行要报错
> > > ```
> > > go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": net/http: TLS handshake timeout
> > > ```
> > > 
> > > 
> > > 请问这是什么原因？还要配置什么不
> > 
> > 
> > 根目录 先执行  go install 安全依赖包呀
> 
> 都说了，代理设置的问题

哦哦 是 超时了。什么网络 还代理失败， go 不是有 国内的代理吗？

**Comment by ruixule** [comment]
> > 
> > 
> > > > > > > 我是用作者代码 在vscode 里面直接编译 执行的. 再抢购完成前不要动浏览器, 可以刷手机看看购物车是否成功.在去浏览器结算.
> > > > > > 
> > > > > > 
> > > > > > 请问装的什么插件执行的编译，还是使用的`go build`命令呢？
> > > > > 
> > > > > 
> > > > > cmd 目录下 执行 go build 会生成 cmd.exe 直接 POWERSHELL执行 就可以了。brwoserPath 参数 手动指定浏览器路径。
> > > > 
> > > > 
> > > > 我这边执行要报错
> > > > ```
> > > > go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": net/http: TLS handshake timeout
> > > > ```
> > > > 
> > > > 
> > > > 请问这是什么原因？还要配置什么不
> > > 
> > > 
> > > 根目录 先执行  go install 安全依赖包呀
> > 
> > 都说了，代理设置的问题
> 
> 哦哦 是 超时了。什么网络 还代理失败， go 不是有 国内的代理吗？

你没有设置好，有国内代理，你要设置呀，

**Comment by Xzw111222** [comment]
嗯嗯感谢两位的回复，改了一个国内可访问的代理。能正常执行了

**Comment by ruixule** [comment]
感谢学到了点，东西
