### ISSUE TITLE
大佬，看下我这个是啥原因

### ISSUE THREAD

**Issue by sandglasstu** [zqjzqj/mtSecKill#13]
没用过go，看你其他回答是直接双击运行，但是我这双击无效，命令行一直报这个
![image](https://user-images.githubusercontent.com/12029190/103858304-0967ba80-50f3-11eb-8d84-5df50a262a50.png)

**Comment by zqjzqj** [comment]
这是你的go代理问题 可以直接在发布版下已经编译好的包 运行即可

**Comment by sandglasstu** [comment]
多谢，明天再试试看
