### ISSUE TITLE
3.6无法获取抢购链接

### ISSUE THREAD

**Issue by cssjidi** [zqjzqj/mtSecKill#133]
您好，作者。我下载了3.6去运行，结果发现无法获取抢购链接。我随便找了一个秒杀商品来测试的。
![image](https://user-images.githubusercontent.com/8515692/104558136-4a287c00-567d-11eb-911c-014908c91b2a.png)

**Comment by zqjzqj** [comment]
只有需要预约类型的商品才可以



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cssjidi"<notifications@github.com&gt;; 
发送时间: 2021年1月14日(星期四) 下午3:30
收件人: "zqjzqj/mtSecKill"<mtSecKill@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [zqjzqj/mtSecKill] 3.6无法获取抢购链接 (#133)





 
您好，作者。我下载了3.6去运行，结果发现无法获取抢购链接。我随便找了一个秒杀商品来测试的。

**Comment by cssjidi** [comment]
Gotcha，thanks.
