### ISSUE TITLE
这个错误是正常的吗？ ERROR: received DOM.documentUpdated when there's no top-level frame

### ISSUE THREAD

**Issue by tlee1987** [zqjzqj/mtSecKill#16]
2021/01/07 19:56:58 ERROR: received DOM.documentUpdated when there's no top-level frame
2021/01/07 19:56:59 ERROR: received DOM.documentUpdated when there's no top-level frame
2021/01/07 19:57:04 ERROR: received DOM.documentUpdated when there's no top-level frame

**Comment by tlee1987** [comment]
已经在其他issue中找到了答案

**Comment by laggage** [comment]
@tlee1987 请问哪个issue可以找到答案啊？
