### ISSUE TITLE
大佬 错误代码 是不是需要修改链接啊？

### ISSUE THREAD

**Issue by dongpei151** [zqjzqj/mtSecKill#18]
E:\桌面\mtSecKill-master\cmd> go run main.go
go: github.com/axgle/mahonia@v0.0.0-20180208002826-3358181d7394: Get "https://proxy.golang.org/github.com/axgle/mahonia/@v/v0.0.0-20180208002826-3358181d7394.mod": dial tcp 216.58.200.241:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by dongpei151** [comment]
另外给大家一段获取eid和fp的html代码
<html>
    <head></head>
    <body>
        <div id="info">获取中……</div>
        <hr>
        <div id="eid"></div>
        <div id="fp"></div>
    </body>
</html>

<script src="https://gias.jd.com/js/td.js"></script>

<script>
    setTimeout(function () {
        try {
            getJdEid(function (eid, fp, udfp) {
                document.getElementById('info').innerText = '请把下面的内容复制到配置文件 config.ini 中的对应位置';
                document.getElementById('eid').innerText = 'eid = ' + eid;
                document.getElementById('fp').innerText = 'fp = ' + fp;
            });
        } catch (e) {
            document.getElementById('info').innerText = e;
        }
    }, 1000);
</script>

**Comment by zqjzqj** [comment]
设置golang的代理，或者直接下载发布版的文件

**Comment by dongpei151** [comment]
好的 大佬  我试试

**Comment by dongpei151** [comment]
京东eid和fp参数获取方式
https://zhuanlan.zhihu.com/p/342219064

**Comment by dongpei151** [comment]
Windows 解决办法
打开你的 PowerShell 并执行

C:\> $env:GO111MODULE = "on"
C:\> $env:GOPROXY = "https://goproxy.cn"
或者

1. 打开“开始”并搜索“env”
2. 选择“编辑系统环境变量”
3. 点击“环境变量…”按钮
4. 在“<你的用户名> 的用户变量”章节下（上半部分）
5. 点击“新建…”按钮
6. 选择“变量名”输入框并输入“GO111MODULE”
7. 选择“变量值”输入框并输入“on”
8. 点击“确定”按钮
9. 点击“新建…”按钮
10. 选择“变量名”输入框并输入“GOPROXY”
11. 选择“变量值”输入框并输入“https://goproxy.cn”
12. 点击“确定”按钮
完成。
macOS 或 Linux 解决办法
打开你的终端并执行

$ export GO111MODULE=on
$ export GOPROXY=https://goproxy.cn
或者

$ echo "export GO111MODULE=on" >> ~/.profile
$ echo "export GOPROXY=https://goproxy.cn" >> ~/.profile
$ source ~/.profile
完成。
