### ISSUE TITLE
macos下五个线程但是只有一个窗口弹出，这个正常吗

### ISSUE THREAD

**Issue by ReCodeLife** [zqjzqj/mtSecKill#203]
macos下五个线程但是只有一个窗口弹出，这个正常吗？好像看介绍应该有5个窗口弹出。。还是说在windows下会比较好？

**Comment by minxiang0101** [comment]
> macos下五个线程但是只有一个窗口弹出，这个正常吗？好像看介绍应该有5个窗口弹出。。还是说在windows下会比较好？

![image](https://user-images.githubusercontent.com/25628026/105015758-d91e0580-5a7c-11eb-9b31-cdbcf6ebbbed.png)
这个有多少说明有多少线程

**Comment by ReCodeLife** [comment]
> > macos下五个线程但是只有一个窗口弹出，这个正常吗？好像看介绍应该有5个窗口弹出。。还是说在windows下会比较好？
> 
> ![image](https://user-images.githubusercontent.com/25628026/105015758-d91e0580-5a7c-11eb-9b31-cdbcf6ebbbed.png)
> 这个有多少说明有多少线程

谢谢 那线程数是对的
