### ISSUE TITLE
自己编译的时候，浏览器路径怎么填都不对，macOS系统

### ISSUE THREAD

**Issue by msn1983aa** [zqjzqj/mtSecKill#211]
var brwoserPath = flag.String("execPath", "/Applications/Google/Chrome.app/Contents/MacOS/GoogleChrome", "浏览器执行路径，路径不能有空格")

路劲如上，执行的时候提示
默认浏览器执行路径未找到，/Applications/Google/Chrome.app/Contents/MacOS/GoogleChrome  请重新输入：

求指导

**Comment by Colingaoyin** [comment]
func main() {
	var err error

	if *isFileLog {
		logs.AllowFileLogs()
	}

	execPath := ""
写在这儿试一试

**Comment by msn1983aa** [comment]
> func main() {
> var err error
> 
> ```
> if *isFileLog {
> 	logs.AllowFileLogs()
> }
> 
> execPath := ""
> ```
> 
> 写在这儿试一试

谢谢，但还是一样的错误信息，留空或者填上都不行，应该还是路径没写对，但是把chrome拖进终端后显示的路径也不对

**Comment by msn1983aa** [comment]
去百度了下搞定了，
显示包内容，进入macos文件夹，选中google chrome，option+cmd+c，路径才对，直接拖入终端里的不对
终端拖入后错误的是：/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
正确的是：/Applications/Google Chrome.app/Contents/MacOS/Google Chrome

**Comment by Colingaoyin** [comment]
直接chrome浏览器输入：chrome://version/，找到可执行路径就好了 "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" . 原来是你的路径有问题
