### ISSUE TITLE
CPU占用率过高

### ISSUE THREAD

**Issue by pdso** [zqjzqj/mtSecKill#52]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/8196592/104259363-3c77c880-54bc-11eb-946f-effd220af8f6.png">

**Comment by pdso** [comment]
到了抢购时间之后，cpu使用率就降下来了。

**Comment by STFQ** [comment]
我的也是，不知道为什么呢，要不是听到有风扇声我都不会去在意的

**Comment by pdso** [comment]
不抢了。
