### ISSUE TITLE
Mac版的如何使用？

### ISSUE THREAD

**Issue by AnoldmanLiSir** [zqjzqj/mtSecKill#68]
你好作者，请问Mac版的如何使用？

**Comment by chenlongchn** [comment]
同求

**Comment by zqjzqj** [comment]
readme里有说明 可以仔细看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenlongchn"<notifications@github.com&gt;; 
发送时间: 2021年1月12日(星期二) 下午3:21
收件人: "zqjzqj/mtSecKill"<mtSecKill@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [zqjzqj/mtSecKill] Mac版的如何使用？ (#68)





 
同求

**Comment by chenlongchn** [comment]
给程序一个777的权限就好了sudo chmod -R 777 mtSecKill.mac

**Comment by Ge3kXm** [comment]
> 给程序一个777的权限就好了sudo chmod -R 777 mtSecKill.mac

然后呢？双击？

**Comment by henshiXINfena** [comment]
小白真的是看的一脸懵逼

**Comment by morgan11-aa** [comment]
麻烦再回复下？.mac 文件在终端如何执行？

**Comment by alterem** [comment]
.mac 文件在终端如何执行？

**Comment by alterem** [comment]
> 麻烦再回复下？.mac 文件在终端如何执行？

在终端执行 ./mtSecKill.mac

**Comment by AnoldmanLiSir** [comment]
统一总结回复下 先给文件一个**执行**的权限
`sudo chmod -R 777 mtSecKill.mac`
然后在**终端执行**
` ./mtSecKill.mac`
