### ISSUE TITLE
用的最新版，仍然报“空数据”错误

### ISSUE THREAD

**Issue by dover** [zqjzqj/mtSecKill#88]
![QQ截图20210113100514](https://user-images.githubusercontent.com/8148653/104397095-f9365c00-5586-11eb-9fb0-dfa2988e5b1b.jpg)

**Comment by zqjzqj** [comment]
这个空数据跟昨天的不是同一个问题 这个是正常的 因为服务器500了，不过今天是有人抢到的，各位坚持吧

**Comment by 371367059** [comment]
今天页面没有跳转

**Comment by feng241x** [comment]
今天的版本也有问题吧？我这里都不自动刷新的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zqjzqj"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 上午10:14
收件人: "zqjzqj/mtSecKill"<mtSecKill@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [zqjzqj/mtSecKill] 用的最新版，仍然报“空数据”错误 (#88)





 
这个空数据跟昨天的不是同一个问题 这个是正常的 因为服务器500了，不过今天是有人抢到的，各位坚持吧
 
&mdash;

**Comment by Ray18** [comment]
一直等待时间到达 ，到了10点还是不动

**Comment by dogezhou** [comment]
> 这个空数据跟昨天的不是同一个问题 这个是正常的 因为服务器500了，不过今天是有人抢到的，各位坚持吧

真的吗？

**Comment by dover** [comment]
> 这个空数据跟昨天的不是同一个问题 这个是正常的 因为服务器500了，不过今天是有人抢到的，各位坚持吧

谢谢大佬回复。
