### ISSUE TITLE
抢购链接问题

### ISSUE THREAD

**Issue by zhangyu789** [zqjzqj/mtSecKill#94]
https://marathon.jd.com/seckill/seckill.action?=skuId=100012043978......

链接？后面这个=有用么？是不是多余的？

**Comment by zqjzqj** [comment]
大意了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zyzyzy"<notifications@github.com&gt;; 
发送时间: 2021年1月13日(星期三) 中午11:08
收件人: "zqjzqj/mtSecKill"<mtSecKill@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [zqjzqj/mtSecKill] 抢购链接问题 (#94)





 
https://marathon.jd.com/seckill/seckill.action?=skuId=100012043978......
 
链接？后面这个=有用么？是不是多余的？

**Comment by indomitableXiaoNan** [comment]
这就尴尬了
